server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  security:
    user:
      name: admin
      password: admin123
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: train-service-trains
          uri: lb://TRAIN-SERVICE
          predicates:
            - Path=/trains/**
        - id: train-service-booking
          uri: lb://TRAIN-SERVICE
          predicates:
            - Path=/booking/**
        - id: ticket-service
          uri: lb://TICKET-SERVICE
          predicates:
            - Path=/tickets/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: myVerySecretKeyForJwtSigningThatIsVeryLong1234567890

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true