server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  profiles: docker
  datasource:
    url: jdbc:mysql://mysql:3306/userdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: appuser
    password: apppassword
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

jwt:
  secret: myVerySecretKeyForJwtSigningThatIsVeryLong1234567890
  expiration: 86400000
